name: Orchestration & Release

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    tags: [ "v*" ]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Initalize
        id: init
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [[ "${{ github.ref }}" =~ ^refs/tags/v.*$ ]]; then
            TAG_NAME="${GITHUB_REF#refs/tags/}"   
            [[ "$(python version.py | tr -d '\n')" == "${GITHUB_REF#refs/tags/v}" ]] || (echo "❌ Version mismatch!" && exit 1)
            echo "release_name=$TAG_NAME" >> $GITHUB_OUTPUT
            echo "is_tag=true" >> $GITHUB_OUTPUT
          else
            gh api repos/${{ github.repository }}/releases/tags/__beta__ --jq '.assets[].id' 2>/dev/null | xargs -r -I {} gh api repos/${{ github.repository }}/releases/assets/{} -X DELETE 2>/dev/null || true
            echo "release_name=__beta__" >> $GITHUB_OUTPUT
            echo "is_tag=false" >> $GITHUB_OUTPUT
          fi

      - name: Initialize release body
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.init.outputs.RELEASE_NAME }}
          name: ${{ steps.init.outputs.RELEASE_NAME }}
          draft: false
          prerelease: ${{ steps.init.outputs.IS_TAG == 'false' }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body_path: .github/workflows/release_template.md



  # cmake:
  #   uses: ./.github/workflows/cmake.yml
  #   needs: [init]

  # wheel:
  #   uses: ./.github/workflows/wheels.yml
  #   needs: [init]

  # release:
  #   # needs: [cmake, wheel]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download all artifacts
  #       uses: actions/download-artifact@v8
          
  #     - name: List dist directory
  #       run: tree --du -shaC . 

        

      # - name: Create release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: __beta__
      #     name: Beta Release
      #     body: |
      #       ## Artifacts

      #       | Name | Description |
      #       |------|------------|
      #       | cmake-artifact | CMake build |
      #       | wheel-artifact | Python wheel |
      #       | go-artifact | Go binary |
      #     files: |
      #       **/*
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

